In [1]:
# Import libraries
import pandas as pd
#from pandas import ExcelWriter
#from pandas import ExcelFile
#import datetime
#import matplotlib as plt
import numpy as np

In [2]:
# Load jax fc file
jax_fc_file = "Resources/JAX FC.csv"

# Read csv file into DataFrame, set Item as index
#jax_fc = pd.read_csv(jax_fc_file, index_col = "Item", parse_dates=["Date"])
jax_fc = pd.read_csv(jax_fc_file, index_col = "Item")
jax_fc.head()

,Bucket,Date,End Date,Number of Buckets,Current,Original,Total,Confidence(%),Project Number,Unnamed: 10,Task Number,Line,Comment,Forecast,[ ]
Item,,,,,,,,,,,,,,,
YT04906-089.50,Days,3/16/2021,NaN,1,22,22,22,100,NaN,NaN,NaN,NaN,CAT 41.00,JAX-FCST,.
YT04906-089.50,Days,4/20/2021,NaN,1,33,33,33,100,NaN,NaN,NaN,NaN,CAT 41.00,JAX-FCST,.
YT04906-089.50,Days,5/18/2021,NaN,1,21,21,21,100,NaN,NaN,NaN,NaN,CAT 41.00,JAX-FCST,.
YT04906-089.50,Days,6/15/2021,NaN,1,58,58,58,100,NaN,NaN,NaN,NaN,CAT 41.00,JAX-FCST,.
YT04906-089.50,Days,7/20/2021,NaN,1,36,36,36,100,NaN,NaN,NaN,NaN,CAT 41.00,JAX-FCST,.

In [3]:
# Remove extra columns 
jax_fc = jax_fc[["Date", "Current", "Comment"]]
jax_fc.head()

                     Date  Current    Comment
Item
YT04906-089.50  3/16/2021       22  CAT 41.00
YT04906-089.50  4/20/2021       33  CAT 41.00
YT04906-089.50  5/18/2021       21  CAT 41.00
YT04906-089.50  6/15/2021       58  CAT 41.00
YT04906-089.50  7/20/2021       36  CAT 41.00